version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: pg-server
    restart: always
    environment:
      POSTGRES_USER: collab_user
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: collab_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
